### ISSUE TITLE
Modify for more general use?

### ISSUE THREAD

**Issue by crabdancing** [LunaSquee/mc_curse_modpack_downloader#2]
I'd like to create a private modpack for use with my friends. My use case is: I want to simply have a plaintext file listing every mod in the modpack, then have the program install/update the pack.

Enhancing this program to allow downloading a local modpack specification would really help out with this sort of thing!

**Comment by crabdancing** [comment]
Never mind! I went ahead an wrote my own implementation. It's [here](https://github.com/alxpettit/MMOBS) if anyone's interested.

**Comment by LunaSquee** [comment]
Did it anyway, 6fb151f.

**Comment by crabdancing** [comment]
Showoff :rofl:

**Comment by crabdancing** [comment]
Awesome work, BTW :3 I quite like how you did it!

**Comment by LunaSquee** [comment]
Haha :P Thanks
